<?php declare(strict_types=1);

use Marco\LandingPages\ViewModel\ActivityProducts;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var $activityProducts ActivityProducts */
/** @var $block Template */
/** @var $escaper Escaper */

$activityProducts = $block->getData('activity_products');
$products = $activityProducts->getProducts();
?>

<style>
.label {
    font-weight: 700;
}
</style>

<h2><?= __('Products View Model') . '(' . $products->getSize() . ')'?></h2>

<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 30px;">

    <?php foreach ($products as $product): ?>

        <?php $price = $product->getFinalPrice(); ?>
        <?php $currency = $activityProducts->getCurrencyAndPrice($price); ?>
        <?php $productUrl = $escaper->escapeUrl($product->getProductUrl()); ?>
        <?php $id = $product->getId(); ?>
        <?php $imageUrl = $escaper->escapeUrl($activityProducts->getImageUrl($id)); ?>

        <table>
            <tr>
                <td class="label"><?= __('Name') ?></td>
                <td><a href="<?= $productUrl ?>"><?= $product->getName() ?></a></td>
            </tr>
            <tr>
                <td class="label"><?= __('SKU') ?></td>
                <td><?= $product->getSku() ?></td>
            </tr>
            <tr>
                <td class="label"><?= __('Price') ?></td>
                <td>
                    <?= $currency ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Image') ?></td>
                <td><img src="<?= $imageUrl ?>"></td>
            </tr>
            <tr>
                <td class="label"><?= __('Activity') ?></td>
                <td>
                    <?php $activities_id = explode(',', $product->getData('activity')); ?>
                    <?php $values = []; ?>

                    <?php foreach($activities_id as $activity_id): ?>
                        <?php $attribute = $product->getResource()->getAttribute('activity'); ?>
                        <?php $values[] = $attribute->getSource()->getOptionText($activity_id); ?>
                    <?php endforeach;?>
                       
                    <?php $activities_values = implode(', ', $values); ?>
                    <?= $activities_values ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Link') ?></td>
                <td><?= $productUrl ?></td>
            </tr>
        </table>

        <!-- <?php dump($product->getData()) ?> -->

    <?php endforeach ?>

    <!-- <?php dump($products->getData()) ?> -->

</div>
