<?php declare(strict_types=1);

use Marco\LandingPages\ViewModel\ActivityProducts;
use Magento\Framework\Escaper;

/** @var $block ActivityProducts */
/** @var $escaper Escaper */

$attributeName = 'activity';
$optionText = 'Gym';
$products = $block->getProducts($attributeName, $optionText);
?>

<style>
.label {
    font-weight: 700;
}
</style>

<h2><?=  $optionText . __(' Products Block') . '(' . $products->getSize() . ')' ?></h2>

<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 30px;">

    <?php foreach ($products as $product): ?>

        <table>
            <tr>
                <td class="label"><?= __('Name') ?></td>
                <td><a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"><?= $product->getName() ?></a></td>
            </tr>
            <tr>
                <td class="label"><?= __('SKU') ?></td>
                <td><?= $product->getSku() ?></td>
            </tr>
            <tr>
                <td class="label"><?= __('Price') ?></td>
                <td>
                    <?= $block->getCurrencyAndPrice($product->getFinalPrice()) ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Image') ?></td>
                <td><img src="<?= $escaper->escapeUrl($block->getImageUrl($product->getId())) ?>"></td>
            </tr>
            <tr>
                <td class="label"><?= __('Activity') ?></td>
                <td>
                    <?= $optionText ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Link') ?></td>
                <td><?= $escaper->escapeUrl($product->getProductUrl()) ?></td>
            </tr>
        </table>

        <!-- <?php dump($product->getData()) ?> -->

    <?php endforeach ?>

    <!-- <?php dump($products->getData()) ?> -->

</div>
