<?php declare(strict_types=1);

use Marco\LandingPages\ViewModel\ActivityProducts;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var $activityProducts ActivityProducts */
/** @var $block Template */
/** @var $escaper Escaper */

$activityProducts = $block->getData('activity_products');
$products = $activityProducts->getProducts();
?>

<style>
.label {
    font-weight: 700;
}
</style>

<h2><?= __('Products View Model') . '(' . $products->getSize() . ')' ?></h2>

<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 30px;">

    <?php foreach ($products as $product): ?>

        <table>
            <tr>
                <td class="label"><?= __('Name') ?></td>
                <td><a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"><?= $product->getName() ?></a></td>
            </tr>
            <tr>
                <td class="label"><?= __('SKU') ?></td>
                <td><?= $product->getSku() ?></td>
            </tr>
            <tr>
                <td class="label"><?= __('Price') ?></td>
                <td>
                    <?= $activityProducts->getCurrencyAndPrice($product->getFinalPrice()) ?>
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Image') ?></td>
                <td><img src="<?= $escaper->escapeUrl($activityProducts->getImageUrl($product->getId())) ?>"></td>
            </tr>
            <tr>
                <td class="label"><?= __('Activity') ?></td>
                <td>
                    <?php if (is_array($product->getAttributeText('activity'))) : ?>
                        <?php $html = [] ?>

                        <?php foreach ($product->getAttributeText('activity') as $activity) : ?>
                            <?php $html[] = $escaper->escapeHtml(__($activity)) ?>
                            <li>
                                <?= $escaper->escapeHtml(__($activity)) ?>
                            </li>
                        <?php endforeach ?>

                        <?= implode(', ', $html) ?>
                        <?= $product->getAttribute('activity') ?>

                    <?php else : ?>

                        <li>
                            <?= $escaper->escapeHtml(__($product->getAttributeText('activity'))) ?>
                            <?= $product->getAttribute('activity') ?>
                        </li>

                    <?php endif ?>

                    <!-- Example with Option Text parameter
                    <?php $activities_id = explode(',', $product->getData('activity')); ?>
                    <?php $values = []; ?>

                    <?php foreach($activities_id as $activity_id): ?>
                        <?php $attribute = $product->getResource()->getAttribute('activity'); ?>
                        <?php $values[] = $attribute->getSource()->getOptionText($activity_id); ?>
                    <?php endforeach;?>
                       
                    <?= implode(', ', $values); ?>
                    -->
                </td>
            </tr>
            <tr>
                <td class="label"><?= __('Activity ID') ?></td>
                <td><?= $product->getData('activity') ?></td>
            </tr>
            <tr>
                <td class="label"><?= __('Link') ?></td>
                <td><?= $escaper->escapeUrl($product->getProductUrl()) ?></td>
            </tr>
        </table>

        <!-- <?php dump($product->getData()) ?> -->

    <?php endforeach ?>

    <!-- <?php dump($products->getData()) ?> -->

</div>
