<?php declare(strict_types=1);

use Marco\LandingPages\ViewModel\FeaturedCategories;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var $featuredCategories FeaturedCategories */
/** @var $block Template */
/** @var $escaper Escaper */

$featuredCategories = $block->getData('featured_categories');
$categories = $featuredCategories->getCategories(2, 3, 'name');
?>

<h2><?= __('Categories View Model') ?></h2>
<ul style="display: flex; column-gap: 20px; list-style-type: none; padding: 0;">
    <?php foreach ($categories as $category): ?>

        <li>
            <a href="<?= $escaper->escapeUrl($category->getUrl()) ?>">
                <?= $category->getName() ?>
            </a>
            <!-- <?php dump($category->getData()); ?> -->
        </li>

    <?php endforeach ?>
</ul>
