<?php declare(strict_types=1);

use Marco\LandingPages\ViewModel\ProductViewModel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var $block Template */
/** @var $productViewModel ProductViewModel */
/** @var $escaper Escaper */

$productId = 2;
$productViewModel = $block->getData('product_view_model');
$product = $productViewModel->getProduct($productId);
$price = $product->getFinalPrice();
$currency = $productViewModel->getCurrencyAndPrice($price);
$productUrl = $escaper->escapeUrl($product->getProductUrl());
$imageUrl = $escaper->escapeUrl($productViewModel->getImageUrl($productId));
?>

<style>
.label {
    font-weight: 700;
}

tr td:first-child {
    width: 20%;
}
</style>

<div>
    <h2><?= __('Product Information View Model') ?></h2>
    <table>
        <tr>
            <td class="label"><?= __('Name') ?></td>
            <td><a href="<?= $productUrl ?>"><?= $product->getName() ?></a></td>
        </tr>
        <tr>
            <td class="label"><?= __('SKU') ?></td>
            <td><?= $product->getSku() ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Price') ?></td>
            <td><?= $currency ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Image Url') ?></td>
            <td>
                <?= $imageUrl ?><br>
                <img src="<?= $imageUrl ?>">
            </td>
        </tr>
        <tr>
            <td class="label"><?= __('Link') ?></td>
            <td><?= $productUrl ?></td>
        </tr>
    </table>
    <!-- <?php dump($product->getData()) ?> -->
</div>
