<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use FisheyeAcademy\LayoutBlocks\ViewModel\ProductViewModel;
use Magento\Framework\Escaper;

/* @var $block Template */
/* @var $productViewModel ProductViewModel */
/* @var $escaper Escaper */

$productViewModel = $block->getData('product_view_model');
$product = $productViewModel->getProduct();
$productUrl = $escaper->escapeUrl($product->getProductUrl());
?>

<style>
.label {
    font-weight: 700;
}
</style>

<div>
    <h2><?= __('Product Information') ?></h2>
    <table>
        <tr>
            <td class="label"><?= __('SKU') ?></td>
            <td><?= $product->getSku() ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Name') ?></td>
            <td><?= $product->getName() ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Price') ?></td>
            <td><?= $product->getFinalPrice() ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Image') ?></td>
            <td><?= $product->getData('small_image') ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Link') ?></td>
            <td><a href="<?= $productUrl ?>"><?= $productUrl ?></a></td>
        </tr>
    </table>
    <?php dump($product->getData()) ?>
</div>
